# Generated by Django 6.0 on 2025-12-06 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OnSale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_on_sale', models.BooleanField()),
                ('desc', models.TextField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='receipts/')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_taxed', models.BooleanField()),
                ('desc', models.TextField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(max_length=500)),
                ('shopping_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_list', to='main.category')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_list', to='main.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='main.item')),
                ('is_on_sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_list', to='main.onsale')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_list', to='main.receipt')),
                ('is_taxed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_list', to='main.tax')),
            ],
        ),
    ]
