# Generated by Django 6.0 on 2025-12-07 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='shopping_date',
        ),
        migrations.AddField(
            model_name='receipt',
            name='shopping_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
