# Generated by Django 6.0 on 2025-12-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_itemlist_shopping_date_receipt_shopping_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='name',
            field=models.TextField(default='2025-12-06', max_length=255, unique=True),
        ),
    ]
