# Generated by Django 6.0.4 on 2026-05-01 03:45

from django.db import migrations

def seeding_data(apps, schema_editor):
    print('seeding data')
    Tax = apps.get_model('main', 'Tax')
    OnSale = apps.get_model('main', 'OnSale')
    
    if not Tax.objects.exists():
        print('seeding tax data')
        Tax.objects.create(is_taxed=True, desc="Yes").save()
        Tax.objects.create(is_taxed=False, desc="No").save()

    if not OnSale.objects.exists():
        print('seeding on sale data')
        OnSale.objects.create(is_on_sale=True, desc="Yes").save()
        OnSale.objects.create(is_on_sale=False, desc="No").save()

    print('finished seeding data')

def reverse_seeding_data(apps, schema_editor):
    Tax = apps.get_model('main', 'Tax')
    OnSale = apps.get_model('main', 'OnSale')

    if Tax.objects.exists():
        print('delete tax data')
        Tax.objects.all().delete()

    if OnSale.objects.exists():
        print('delete sale data')
        OnSale.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_receipt_name"),
    ]
    
    operations = [
        migrations.RunPython(seeding_data, reverse_seeding_data),
    ]