# Generated by Django 6.0 on 2026-05-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.TextField(default='2026-05-14', max_length=255),
        ),
    ]
