# Generated by Django 6.0 on 2026-05-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_receipt_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.TextField(default='2026-05-16', max_length=255),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='shopping_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
