# Generated by Django 6.0 on 2026-05-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_receipt_created_at_alter_receipt_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='shopping_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
